### ISSUE TITLE
shared-buffer worth investigating for safe, untrusted ipc?

### ISSUE THREAD

**Issue by PrototypeNM1** [dicej/ipmpsc#1]
> `shared-buffer` provides support for safely operating on memory buffers which are shared with another process which is untrusted.
[shared-buffer](https://fuchsia.googlesource.com/fuchsia/+/master/garnet/public/rust/shared-buffer/src/lib.rs)

Thought it was worth bringing to your attention, my apologies if you're already familiar with it.

**Comment by dicej** [comment]
Hi @PrototypeNM1.  So sorry for not responding sooner -- I didn't see this until now.  Unfortunately, that link doesn't seem to work anymore.  Do you happen to know where it moved?

**Comment by PrototypeNM1** [comment]
No worries, here's an updated link

**Comment by PrototypeNM1** [comment]
[Here](https://fuchsia.googlesource.com/fuchsia/+/master/src/lib/shared-buffer/src/lib.rs)'s an updated link, or if you need to find it again a crate in Fuschia called shared-buffer.

**Comment by dicej** [comment]
Thanks!  That project could definitely be worth adopting for use in `ipmpsc`, or at least referenced as a model for how to provide sound access to untrusted memory in Rust.  Not sure when I'll have time to do either of those things, but I'll put it on my todo list.

**Comment by dicej** [comment]
I'm going to close this one since I don't see it going anywhere in the forseeable future.

`ipmpsc`'s mission is to facilitate IPC between mutually trusting processes, each of which uses only `ipmpsc` to access the shared memory.  If you need to do shared memory with one or more untrusted processes, Fuschia's shared-buffer is the way to go, but that level of paranoia (and the associated performance cost of extra copies) is not necessary if you can guarantee all processes will follow the rules (e.g. embedded systems and isolated containers).

That said, if someone wants to add a robust "untrusted" mode to `ipmpsc`, I'm happy to discuss it.  Hard to imagine how a shared memory ring buffer could possibly work in an adversarial context, though.
