### ISSUE TITLE
Using Stdin /  Stdout for IPC

### ISSUE THREAD

**Issue by mmstick** [dicej/ipmpsc#3]
Is it in any way possible to use any `File` or `RawFd` as the basis for a sender and receiver? This is generally how I perform IPC on Linux, using pipes between processes.

**Comment by dicej** [comment]
Hi @mmstick.  Sorry for the late response -- I didn't see this until now.

No, sorry, there's no way to use named or anonymous pipes with this library.  You could do that with the [libc](https://crates.io/crates/libc) crate, though, and you could search crates.io for some higher-level abstractions, e.g. https://crates.io/search?q=pipe.

**Comment by mmstick** [comment]
Was this implemented?

**Comment by dicej** [comment]
Hi @mmstick.  No, it has not been implemented in `ipmpsc`.  What I meant to say in my comment above is that what you describe is available directly from the operating system via e.g. the `libc` and `winapi` crates.  Since those crates already offer traditional IPC functionality, I don't see a need to duplicate it in this library.  And if there's an unmet need for a higher-level abstraction for traditional IPC, then that should probably be a separate crate.
